name: feapkbooking
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Ikon
  cupertino_icons: ^1.0.8
  
  # State Management & Utility
  intl: ^0.20.2
  provider: ^6.0.5
  google_fonts: ^6.3.2
  http: ^1.6.0
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  
  # Package untuk membuat icon
  flutter_launcher_icons: ^0.13.1
  
  # --- BARIS INI BARU DITAMBAHKAN ---
  flutter_native_splash: ^2.4.0 

# Konfigurasi Ikon Launcher
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" 
  min_sdk_android: 21

# --- BLOK INI BARU DITAMBAHKAN ---
# Konfigurasi Splash Screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/icon.png
  android_12:
    image: assets/icon/icon.png
    color: "#FFFFFF"
# -----------------------------------

# Bagian konfigurasi Flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo_PLN.png
    - assets/icon/icon.png